spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
vola:
  api:
    key: ${VOLA_API_KEY}